# Shared constants for PyQtLabGraph components to avoid duplication and circular imports.

_ADAPTIVE_PERFORMANCE_THRESHOLD = 5_000
_ADAPTIVE_PERFORMANCE_RESTORE_THRESHOLD = 3_000

_GRID_LINE_WIDTH = 1
_GRID_Z_VALUE = -10

_AXIS_PEN_WIDTH = 1
_AXIS_LABEL_TOP_MARGIN = "24px"
_AXIS_LABEL_RIGHT_MARGIN = "24px"

_RANGE_PADDING = 0.0

_X_AUTOSCALE_EQUAL_VALUE_MARGIN = 1.0
_Y_AUTOSCALE_EQUAL_VALUE_MARGIN = 1.0
_Y_AUTOSCALE_MARGIN_RATIO = 0.1
